### PR TITLE
Feat/expand config options

### PR DESCRIPTION
**Pull request by JayV30**
Hi! I found your excellent SCORM packager here and while experimenting with it I discovered a few typos in the README.md (vcard.org was expecting vcard.organization in the config.js).

I forked your project and modified the README and a few other things (defaulting to language 'en' - although very possibly you don't want that in yours...)

Changes are relatively minor and should allow a quick review.

It would be great if you could merge these minor changes, but if you do not want to I understand. I wanted to contribute to your project if possible before uploading my fork to npm.

### CODE REVIEW

**Comment by snaemi** [comment]
Hi!

@JayV30 - I recently pulled the latest version of this and it looks like the change you made to include UTC time as part of the output file name has broken things for me. I'll adjust my code accordingly, but wanted to make you aware in case there are other users encountering this.

After generating the package, I then retrieve the output using path.resolve. My assumption was that the file name was based on parameters passed into 'package' (version, name, date, etc.). Since these are all known (set by me), it was easy to determine the file name. However, including the UTC time within the 'buildPackage' code now breaks that assumption.

It seems that the following are viable options:
- Have the user include UTC time when setting 'package.date'
- Make UTC time an additional parameter on 'package', which in turn is used when generating the file name for the output
- Return the file name as part of the callback for 'buildPackage'

In any case, as mentioned, I'll be adjusting things on my side, so I don't have any immediate need for a fix.

**Comment by JayV30** [comment]
Hey sorry about that! I originally thought I was going to just fork the project but then decided to submit a pull request. I hadn't considered the impact of renaming the built archive.

I'll work on restoring it to the original and allowing a timestamp as an option.

**Comment by JayV30** [comment]
@snaemi 

Version 0.2.5 now by default does not add the timestamp to the .zip file output. It is now part of the options object, `package.appendTimeToOutput: true` will add it.

Sorry about the hassle. I did keep the '_v' added before the version, but no timestamp. So the default output looks like this:
`${package.name}_v${package.version}_${package.date}.zip`

I don't have rights to the npm repository to push the changes but have requested it and will push the new version if/when those rights are given.

**Comment by snaemi** [comment]
@JayV30 - thanks for the update and prompt fix! No worries about the hassle. It forced me to revisit that part of my code and (hopefully) make it more robust, which was long overdue. Thanks again!

**Comment by JayV30** [comment]
@snaemi no worries! FYI new version has been published to npm with the changes. Take care!

**Pull request merged**
